-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "purchasePrice" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Sale" ADD COLUMN     "grossProfit" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "SaleItem" ADD COLUMN     "profit" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "purchasePriceSnapshot" DOUBLE PRECISION NOT NULL DEFAULT 0;
